### PR TITLE
Add DijetGAN paper

### PR DESCRIPTION
**Pull request by rdisipio**
Adding new preprint to the bibliography.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@rdisipio Thanks for your PR! We very much appreciate contributions.

To finish this PR can you please fix the hyperlink to INSPIRE and add the additional parts that are outlined in the relevant section in [`CONTRIBUTING.md`](https://github.com/iml-wg/HEP-ML-Resources/blob/master/CONTRIBUTING.md#how-do-i-add-a-paper)?

**Comment by rdisipio** [comment]
I also modified the .bib file. I think it appears as a patch-2 MR.

**Comment by matthewfeickert** [comment]
> I also modified the .bib file. I think it appears as a patch-2 MR.

Okay, that shouldn't have been its own PR as it is still part of the atomic process of adding a new paper. I've closed that PR and git `cherry-pick`ed the respective commit into this PR's branch.

To finish this PR please fix the hyperlink to INSPIRE and add the additional parts that are outlined in the relevant section in [`CONTRIBUTING.md`](https://github.com/iml-wg/HEP-ML-Resources/blob/master/CONTRIBUTING.md#how-do-i-add-a-paper), which I have copied below. Let me know if you have questions about this or the PR.

>### How do I add a paper?
>
>All paper additions should be submitted as a single pull request on a source branch that isn't `master`.
>
>1. Find the paper on [INSPIRE](https://inspirehep.net/?ln=en)
>   - **N.B.:** If you have already found the paper on [arXiv](https://arxiv.org/) you should be able to find the INSPIRE listing linked under "References & Citations"
>2. Get the BibTeX for the paper citation provided by INSPIRE (under "Export" at the bottom of the page)
>3. Add this BibTeX entry to [`tex/HEPML.bib`](https://github.com/iml-wg/HEP-ML-Resources/blob/master/tex/HEPML.bib) in the appropriate chronological position
>4. Add a citation to [`tex/HEPML.tex`](https://github.com/iml-wg/HEP-ML-Resources/blob/master/tex/HEPML.tex) in the appropriate chronological position
>5. `make` and copy the resulting citation into [`papers.md`](https://github.com/iml-wg/HEP-ML-Resources/blob/master/papers.md) in the appropriate chronological position
>   - You will need to add the appropriate hyperlinks. Follow the style used for previous entries.
>6. Add and commit `tex/HEPML.bib`, `tex/HEPML.tex`, and `papers.md` to your pull request

**Comment by matthewfeickert** [comment]
Since it is easy to do I corrected things and am merging this in now.

**Pull request merged**
