### PR TITLE
Update courses

### PR DESCRIPTION
**Pull request by tempse**
- Add the 2017 Stanford lecture on CNNs for visual recognition
- Extend lecturer list for the 2016 course

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@tempse This looks great! Thanks for finding and adding this. Would you mind switching the order though so that the courses are in reverse chronological order (2017 then 2016)?

**Comment by tempse** [comment]
@matthewfeickert Yes, of course. Should be fixed now.

**Comment by matthewfeickert** [comment]
@tempse Looks great! Thanks for your contributions.

Sorry for my slow reply --- I was traveling.

**Comment by tempse** [comment]
@matthewfeickert Thanks! And no worries about the delay. ;)

**Pull request merged**
