### PR TITLE
Add Deep Learning for Physical Sciences Papers

### LINKED ISSUE #21: suggested addition
https://arxiv.org/abs/1711.02633

and a few HEP related ones here:
https://dl4physicalsciences.github.io

I should do PR myself, but on phone right now.

### PR DESCRIPTION
**Pull request by matthewfeickert**
Resolves #21

Add the papers suggested in Issue #21 

- Add "Recursive Neural Networks in Quark/Gluon Tagging"

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@cranmer @mickypaganini @lukedeo @bnachman Can people comment on suggestions for how the Deep Learning for Physical Sciences papers should be cited? Also, let me know if you think I missed any in the below (or if you would remove any):

- [Adversarial learning to eliminate systematic errors: a case study in High Energy Physics](https://dl4physicalsciences.github.io/files/nips_dlps_2017_1.pdf)
- [Deep topology classifiers for a more efficient trigger selection at the LHC](https://dl4physicalsciences.github.io/files/nips_dlps_2017_3.pdf)
- [Convolutional Neural Networks for Electron Neutrino and Electron Shower Energy Reconstruction in the NOvA Detectors](https://dl4physicalsciences.github.io/files/nips_dlps_2017_7.pdf)
- [DeepJet: Generic physics object based jet multiclass classification for LHC experiments](https://dl4physicalsciences.github.io/files/nips_dlps_2017_10.pdf)
- [Calorimetry with Deep Learning: Particle Classification, Energy Regression, and Simulation for High-Energy Physics](https://dl4physicalsciences.github.io/files/nips_dlps_2017_15.pdf)
- [Survey of Machine Learning Techniques for High Energy Electromagnetic Shower Classification](https://dl4physicalsciences.github.io/files/nips_dlps_2017_24.pdf)
- [Tips and Tricks for Training GANs with Physics Constraints](https://dl4physicalsciences.github.io/files/nips_dlps_2017_26.pdf)
- [Particle Track Reconstruction with Deep Learning](https://dl4physicalsciences.github.io/files/nips_dlps_2017_28.pdf)
- [Neural Message Passing for Jet Physics](https://dl4physicalsciences.github.io/files/nips_dlps_2017_29.pdf)

**Comment by bnachman** [comment]
Hi @matthewfeickert,

This is a great resource!  By the way, you may want to consider adding a link to this workshop: https://indico.physics.lbl.gov/indico/event/546/ (you may also be personally interested in the results that were presented!  Sorry it conflicted with the HFSF).

For the NIPS workshop, I would suggest e.g.

M. Paganini, L. de Oliveira, and B. Nachman, Survey of Machine Learning Techniques for High Energy Electromagnetic Shower Classification, Proceedings of the Deep Learning for Physical Sciences Workshop at NIPS (2017).   url: https://dl4physicalsciences.github.io/files/nips_dlps_2017_24.pdf.

Sincerely,
Ben

**Comment by matthewfeickert** [comment]
@bnachman Many thanks! Also, yes(!) thanks for the reminder on the jet physics workshop! It will be added as part of this PR.

**Comment by cranmer** [comment]
Hi all

I was thinking to add all of these papers to INSPIRE. I think INSPIRE will then make a backup copy and provide a canonical bibtex entry. I wanted to discuss with other organizers first. Some are already on the arxiv.

Kyle

**Comment by matthewfeickert** [comment]
I made a few edits from the style Ben suggested to keep in the form that we've been using. If there are any suggested corrections then I can make them.

**Comment by matthewfeickert** [comment]
@cranmer, seems I just missed your post. I think adding them to INSPIRE would be great (especially as everything else in the listing in linked to INSPIRE). Once they're on INSPIRE could you just ping either here or in the original issue (Issue #21) and then I can make a new PR with the changes?

**Pull request merged**
