### PR TITLE
Add HSF list of Python Libraries of Interest to Particle Physics

### LINKED ISSUE #36: link to  HSF-training resources
Add link to [HEP Software Foundation](https://github.com/hsf-training)'s list of [Python Libraries of Interest to Particle Physics](https://github.com/hsf-training/PyHEP-resources)

### PR DESCRIPTION
**Pull request by cranmer**
Resolves #36

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@cranmer Thanks very much for the PR! It is a nice addition.

I agree that placing it under software seems to be the correct choice. To try and make this clearer I also [added a commit](https://github.com/iml-wg/HEP-ML-Resources/pull/37/commits/45348bbd2064892b386b9b7deda39ed3475b9cf6) that groups things under a "Python environments for scientific computing" sublist. [Look good to you](https://github.com/cranmer/HEP-ML-Resources/blob/master/README.md#software)?

**Comment by cranmer** [comment]
I like the idea of that sub-group. The HSF list of resources has other things too though, like workshops, tutorials, etc. It's kind of a parallel effort to this, so maybe worth having a top level section on "Other Resource Lists"

**Comment by matthewfeickert** [comment]
@cranmer Now listed under [Other HEP Resource Collections](https://github.com/cranmer/HEP-ML-Resources/blob/master/README.md#other-hep-resource-collections) (which is also added to the TOC).

**Comment by matthewfeickert** [comment]
@cranmer I'm going to merge this in as there hasn't been any other development on this and I think we covered everything that originally came up. Thanks for the PR!

**Pull request merged**
