### PR TITLE
Add 5th Machine Learning in HEP Summer School

### PR DESCRIPTION
**Pull request by dguest**
Add the [5th Machine Learning in High Energy Physics Summer School 2019](https://indico.cern.ch/event/768915/) to upcoming HEPML summer schools.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@dguest Thanks for the PR! We appreciate contributions. :)

I'm going to go ahead and make a small change of removing the "
Associated Yandex School of Data Analysis" link as the 2019 repo isn't available yet.

**Comment by dguest** [comment]
OK, no objections to that change.

**Comment by jpseixasesilva** [comment]
Do you use BigML in HEP ML ?

**Comment by matthewfeickert** [comment]
@jpseixasesilva This PR isn't really the best place to discuss tangential things, but the short answer is no. As can be seen [from the rest of the listing](https://github.com/iml-wg/HEP-ML-Resources#software) the high energy physics community doesn't endorse any specific proprietary software and has a strong bias towards being users, developers, and contributors of open source.

**Pull request merged**
