### PR TITLE
Adds a past AI Winter School event

### PR DESCRIPTION
**Pull request by theonlyNischal**
Adds information about AI winter school in Nepal. The website contains all the course material taught during the winter school.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@theonlyNischal Thanks for your PR. We appreciate contributions! :)

However, from a quick look it doesn't seem like any of the lectures/resources from this ML school are publicly listed there, and so now that it has passed it doesn't seem to actually be a usable resource. Am I missing a link?

**Comment by theonlyNischal** [comment]
@matthewfeickert Thank you for your response. Now, I have added the link for the course materials.

**Comment by matthewfeickert** [comment]
@theonlyNischal Ah, okay. I see that this is just a Google Drive. Are you one of the organizers of the school? If so, can you host the school contents on the website? I'm rather reluctant to add non-physics orientated resources that don't have clear long term support from an institution.

**Comment by matthewfeickert** [comment]
Closing this as it has been a month without any activity. Feel free to reopen it if open resources supported by the school with long term support become available.

**Pull request closed without merging**
